import { Footer } from '@/components/footer';
import { Navbar } from '@/components/navbar';
import { LenisProvider } from '@/components/providers/lenis-provider';
import { Pointer } from '@/components/ui/pointer';
import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';

import './globals.css';

const displayFont = Poppins({
  variable: '--font-display',
  subsets: ['latin'],
  weight: '500',
});

const bodyFont = Inter({
  variable: '--font-body',
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${displayFont.variable} ${bodyFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LenisProvider>
          <Navbar />
          {children}
          <Footer />
        </LenisProvider>
        <Pointer />
      </body>
    </html>
  );
}
